Motor
pi1-2024-ChicoLiro/ChicoLiro.s-Comand pull request #14
Opened 2024-05-27 19:35 UTC by Angelicahaas

## Descrição

Código para ligar/desligar o motor, e adicionar a funcionalidade de oscilar a velocidade.

## _Issue_ Relacionada
[US 01]: Controlar a Velocidade dos Motores 

## Como Isso Foi Testado?

## Capturas de Tela (se apropriado):

## Tipos de Mudanças

- [ ] _Bug fix_ (alteração que corrige uma _issue_ e não altera funcionalidades já existentes);
- [x] Nova _feature_ (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
- [ ] Alteração disruptiva (_Breaking change_) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);

2024-05-27 19:38 UTC, Angelicahaas commented
testando motor

2024-05-29 14:25 UTC, fsousac commented
A branch tá com conflitos com a main, recomendo atualizá-la @Angelicahaas

2024-05-29 15:57 UTC, DanielRogs requested changes
@Angelicahaas, faz o git pull na sua branch e arruma os conflitos. Depois dá Git Push novamente pra podermos dar merge.

2024-05-29 19:23 UTC, DanielRogs approved these changes
LGTM

2024-05-29 19:27 UTC, LeanArs approved these changes

2024-05-31 20:02 UTC, merged